import sys
import os
import shutil
from werkzeug.security import generate_password_hash

# Add parent directory to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from database import init_db, get_db_direct, calculate_nutri_score

def copy_placeholder():
    # Source image path (generated by tool)
    source_img = r"C:\Users\HP\.gemini\antigravity\brain\6c8ef247-3188-443a-b727-4511ec683dde\product_placeholder_1779545019690.png"
    
    # Destination directory
    dest_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "static", "images", "products")
    os.makedirs(dest_dir, exist_ok=True)
    
    dest_path = os.path.join(dest_dir, "placeholder.png")
    
    if os.path.exists(source_img):
        shutil.copy(source_img, dest_path)
        print(f"Placeholder image copied to {dest_path}")
    else:
        # Create an empty file if source doesn't exist
        with open(dest_path, "wb") as f:
            f.write(b"")
        print(f"Source image not found, created empty placeholder at {dest_path}")

def seed_data():
    # Initialize DB first (create tables if they don't exist)
    init_db()
    
    conn = get_db_direct()
    cursor = conn.cursor()
    
    # 1. Seed Users (if they do not exist)
    admin_pw = generate_password_hash("adminpassword")
    test_pw = generate_password_hash("password123")
    
    cursor.execute("SELECT id FROM users WHERE email = 'admin@amulnutri.ai'")
    if not cursor.fetchone():
        cursor.execute(
            "INSERT INTO users (name, email, password_hash, role) VALUES (?, ?, ?, ?)",
            ("Admin User", "admin@amulnutri.ai", admin_pw, "admin")
        )
        print("Admin user seeded.")
        
    cursor.execute("SELECT id FROM users WHERE email = 'john@example.com'")
    if not cursor.fetchone():
        cursor.execute(
            "INSERT INTO users (name, email, password_hash, role) VALUES (?, ?, ?, ?)",
            ("John Doe", "john@example.com", test_pw, "user")
        )
        print("Test user seeded.")
        
    # 2. Seed Products (Clear existing and re-seed to avoid duplicates/ensure freshness)
    cursor.execute("DELETE FROM products")
    
    # Define a simple recipe JSON for each product (title, ingredients, steps)
    recipes_map = {
        "Amul Gold Full Cream Milk": '[{"title":"Gold Milkshake","ingredients":["200 ml Amul Gold Full Cream Milk","Sugar","Ice cubes"],"steps":["Combine milk, sugar, and ice in a blender","Blend until smooth","Serve chilled"]},{"title":"Creamy Rice Kheer","ingredients":["1 litre Amul Gold Full Cream Milk","1/4 cup Basmati Rice","1/2 cup Sugar","Cardamom powder","Almond slivers"],"steps":["Rinse rice and soak for 30 mins","Boil milk, add rice, simmer on low heat till thick","Stir in sugar and cardamom","Garnish with almonds and serve hot or cold"]},{"title":"Homemade Soft Paneer","ingredients":["1 litre Amul Gold Full Cream Milk","2 tbsp Lemon juice or vinegar"],"steps":["Boil the milk in a large pan","Slowly add lemon juice while stirring until whey separates","Strain through a muslin cloth","Press with a heavy weight for 30 minutes, then cut into cubes"]}]',
        "Amul Taaza Toned Milk": '[{"title":"Toned Milk Smoothie","ingredients":["200 ml Amul Taaza Toned Milk","Banana","Honey"],"steps":["Blend all ingredients","Pour into glass","Enjoy"]},{"title":"Spiced Turmeric Milk","ingredients":["200 ml Amul Taaza Toned Milk","1/2 tsp Turmeric powder","Pinch of black pepper","1 tsp Honey"],"steps":["Heat milk in a saucepan until warm","Whisk in turmeric and black pepper","Pour into mug, stir in honey, and drink warm"]}]',
        "Amul Butter": '[{"title":"Butter Garlic Toast","ingredients":["2 slices bread","Amul Butter","Garlic","Salt"],"steps":["Spread butter on bread","Sprinkle garlic and salt","Toast until golden"]},{"title":"Herb Butter Sauce","ingredients":["50g Amul Butter","1 tbsp Mixed herbs","1 tsp Lemon juice"],"steps":["Melt butter on low heat","Stir in herbs and lemon juice","Serve over roasted veggies or pasta"]},{"title":"Butter Pav Bhaji Toast","ingredients":["2 Pav buns","2 tbsp Amul Butter","1 tsp Pav Bhaji Masala"],"steps":["Melt butter on a hot tawa","Sprinkle pav bhaji masala on the butter","Slice pav buns and toast on both sides until crispy"]}]',
        "Amul Processed Cheese": '[{"title":"Cheese Grilled Sandwich","ingredients":["Bread","Amul Processed Cheese","Butter","Tomato","Salt"],"steps":["Butter bread","Add cheese and tomato slices","Grill until cheese melts"]},{"title":"Cheese Macaroni","ingredients":["1 cup Macaroni","1/2 cup grated Amul Processed Cheese","1 tbsp Butter","1/2 cup Milk"],"steps":["Boil macaroni until cooked","Drain and toss with butter and milk","Add grated cheese, stir on low heat until fully melted"]},{"title":"Cheesy Garlic Bread","ingredients":["1 French loaf or bread slices","2 tbsp Butter","Grated Amul Processed Cheese","Garlic paste","Oregano"],"steps":["Mix butter and garlic paste, spread on bread","Top generously with grated cheese and oregano","Bake at 180C for 8-10 minutes until cheese is bubbly"]}]',
        "Amul Kool Milk Shake (Kesar)": '[{"title":"Kesar Milkshake","ingredients":["200 ml Amul Kool Milk Shake (Kesar)","Ice cubes"],"steps":["Blend milkshake with ice","Serve chilled"]},{"title":"Kesar Dry Fruit Delight","ingredients":["200 ml Amul Kool Kesar Milkshake","Chopped almonds and pistachios","1 scoop Vanilla Ice cream"],"steps":["Pour chilled kesar shake into a tall glass","Top with vanilla ice cream","Garnish with chopped dry fruits and serve immediately"]}]',
        "Amul Dahi": '[{"title":"Dahi Parfait","ingredients":["150 g Amul Dahi","Honey","Granola","Fruit pieces"],"steps":["Layer dahi with honey, granola, and fruit","Serve as a healthy snack"]},{"title":"Sweet Lassi","ingredients":["200 g Amul Dahi","3 tbsp Sugar","1/2 cup Cold Water","Pinch of cardamom"],"steps":["Blend dahi, sugar, cold water, and cardamom until frothy","Pour into glasses and serve chilled"]},{"title":"Garlic Dahi Dip","ingredients":["150 g Amul Dahi","1 minced Garlic clove","1/2 tsp Olive oil","Salt and Pepper"],"steps":["Whisk dahi until smooth","Mix in minced garlic, salt, and pepper","Drizzle with olive oil and serve with chips or veggies"]}]',
        "Amul Lassi": '[{"title":"Mango Lassi","ingredients":["200 ml Amul Lassi","Mango pulp","Sugar"],"steps":["Mix all ingredients","Blend until smooth","Serve chilled"]},{"title":"Rose Lassi Cooler","ingredients":["200 ml Amul Lassi","1 tbsp Rose syrup","Ice cubes"],"steps":["Blend Amul Lassi with rose syrup and ice cubes","Pour into a tall glass and serve decorated with rose petals"]}]',
        "Amul Ice Cream (Vanilla)": '[{"title":"Vanilla Ice Cream Sundae","ingredients":["2 scoops Amul Ice Cream (Vanilla)","Chocolate syrup","Cherries"],"steps":["Place ice cream in a bowl","Drizzle syrup","Top with cherries"]},{"title":"Affogato Classic","ingredients":["1 scoop Amul Ice Cream (Vanilla)","1 shot Hot Espresso coffee"],"steps":["Place vanilla ice cream scoop in a cup","Pour hot espresso directly over the ice cream","Serve and enjoy immediately"]}]',
        "Amul Slim & Trim Milk": '[{"title":"Slim Milk Smoothie","ingredients":["200 ml Amul Slim & Trim Milk","Strawberries","Honey"],"steps":["Blend all together","Serve chilled"]},{"title":"Oatmeal Porridge","ingredients":["200 ml Amul Slim & Trim Milk","1/2 cup Rolled oats","1 tsp Honey or maple syrup","Chia seeds"],"steps":["Cook oats in slim milk on medium heat for 5-7 minutes","Stir constantly until creamy","Top with honey and chia seeds"]}]',
        "Amul Paneer": '[{"title":"Paneer Tikka","ingredients":["100 g Amul Paneer","Yogurt","Spices","Lemon juice"],"steps":["Marinate paneer","Skewer and grill","Serve hot"]},{"title":"Paneer Butter Masala","ingredients":["200g Amul Paneer cubes","2 tbsp Amul Butter","1 cup Tomato puree","1/2 cup Fresh cream","Spices"],"steps":["Sauté spices in butter, add tomato puree and cook","Add paneer cubes and simmer for 5 minutes","Stir in fresh cream and serve hot with naan"]},{"title":"Paneer Bhurji","ingredients":["150g scrambled Amul Paneer","1 Onion chopped","1 Tomato chopped","1 Green chili","Spices"],"steps":["Sauté onion, tomato, and chili in a pan","Add spices and scrambled paneer","Toss well, cook for 3 minutes, garnish with coriander"]}]',
        "Amul Ghee": '[{"title":"Ghee Rice","ingredients":["1 cup rice","2 tbsp Amul Ghee","Spices","Vegetables"],"steps":["Cook rice","Temper ghee with spices","Combine and serve"]},{"title":"Ghee Roast Potatoes","ingredients":["3 Boiled potatoes cubed","2 tbsp Amul Ghee","1 tsp Cumin seeds","Turmeric and Chili powder"],"steps":["Heat ghee in a pan, add cumin seeds until they splutter","Add potatoes, turmeric, chili powder, and salt","Sauté on medium-high until potatoes are golden and crispy"]}]',
        "Amul Masti Buttermilk": '[{"title":"Spiced Buttermilk","ingredients":["200 ml Amul Masti Buttermilk","Cumin powder","Salt","Coriander"],"steps":["Whisk buttermilk","Add spices","Serve chilled"]},{"title":"Mint Buttermilk Cooler","ingredients":["200 ml Amul Masti Buttermilk","5-6 Fresh Mint leaves","Pinch of Black Salt"],"steps":["Grind mint leaves into a paste","Blend buttermilk with mint paste and black salt","Serve chilled with ice"]}]',
        "Amul Mithai Mate": '[{"title":"Milk Sweet Dessert","ingredients":["25 g Amul Mithai Mate","Milk","Cardamom"],"steps":["Heat milk","Add Mithai Mate and stir","Simmer until thick"]},{"title":"Instant Coconut Ladoo","ingredients":["100g Amul Mithai Mate","1 cup Desiccated coconut"],"steps":["Mix Mithai Mate and desiccated coconut in a bowl","Roll into small round balls","Coat with dry desiccated coconut and chill"]}]',
        "Amul Pro (Protein Drink)": '[{"title":"Protein Shake","ingredients":["30 g Amul Pro","Water or milk","Banana"],"steps":["Mix powder with liquid","Blend with banana","Drink after workout"]},{"title":"Pro Oats Bowl","ingredients":["30 g Amul Pro","1/2 cup Oats","200 ml Warm Milk"],"steps":["Prepare oats in warm milk","Stir in Amul Pro powder until fully dissolved","Top with sliced banana and enjoy"]}]',
        "Amul Camel Milk": '[{"title":"Camel Milk Smoothie","ingredients":["200 ml Amul Camel Milk","Dates","Honey"],"steps":["Blend all ingredients","Serve chilled"]},{"title":"Camel Milk Chai","ingredients":["150 ml Amul Camel Milk","1 tsp Tea leaves","1 tsp Sugar","Ginger"],"steps":["Boil ginger and tea leaves in 50ml water","Add Camel Milk and sugar, simmer for 3 minutes","Strain and serve hot"]}]',
        "Amul Fresh Cream": '[{"title":"Creamy Pasta Sauce","ingredients":["30 g Amul Fresh Cream","Tomato paste","Garlic","Herbs"],"steps":["Sauté garlic","Add tomato paste and cream","Simmer and toss with pasta"]},{"title":"Creamy Fruit Salad","ingredients":["1 cup Mixed fruits","1/2 cup Amul Fresh Cream","1 tbsp Honey"],"steps":["Whip fresh cream with honey until light","Toss in chopped mixed fruits","Chill for 1 hour before serving"]}]',
        "Amul Shrikhand (Elaichi)": '[{"title":"Shrikhand","ingredients":["100 g Amul Shrikhand","Saffron","Sugar"],"steps":["Whisk together","Chill and serve with nuts"]},{"title":"Shrikhand Puri Delight","ingredients":["100 g Amul Shrikhand (Elaichi)","Hot fried puris"],"steps":["Scoop chilled Shrikhand into a serving bowl","Serve immediately as a classic pairing with hot crispy puris"]}]',
        "Amul Basundi": '[{"title":"Basundi","ingredients":["100 g Amul Basundi","Cardamom","Almond slivers"],"steps":["Heat basundi","Add cardamom and nuts","Serve warm or chilled"]},{"title":"Basundi Fruit Fusion","ingredients":["100 g Amul Basundi","Apple and banana slices"],"steps":["Chill Basundi thoroughly","Fold in chopped fresh fruits","Serve in small dessert bowls garnished with pistachios"]}]',
        "Amul Gulab Jamun Mix": '[{"title":"Gulab Jamun","ingredients":["50 g Amul Gulab Jamun Mix","Milk","Sugar syrup"],"steps":["Prepare dough","Fry balls","Soak in syrup"]},{"title":"Dry Gulab Jamun Coconut","ingredients":["50 g Amul Gulab Jamun Mix","Milk","Sugar syrup","Desiccated coconut"],"steps":["Prepare and fry gulab jamuns, soak in syrup for 2 hours","Drain excess syrup","Roll each jamun in desiccated coconut and serve dry"]}]',
        "Amul Cheese Spread (Spicy Garlic)": '[{"title":"Spicy Garlic Cheese Dip","ingredients":["15 g Amul Cheese Spread","Garlic","Chili flakes","Cream cheese"],"steps":["Mix all ingredients","Serve with crackers"]},{"title":"Cheesy Garlic Toasties","ingredients":["2 slices bread","1 tbsp Amul Cheese Spread (Spicy Garlic)","Butter"],"steps":["Lightly butter bread slices","Spread a generous layer of spicy garlic cheese spread","Toast on a pan until bread is crispy and cheese is warm"]}]'
    }

    products_to_seed = [
        {
            "name": "Amul Gold Full Cream Milk",
            "category": "Milk",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 87.0,
            "protein": 3.2,
            "fat": 6.0,
            "carbs": 5.0,
            "sugar": 0.0,
            "sodium": 50.0,
            "serving_size": "200 ml",
            "description": "Rich and creamy pasteurized full cream milk, perfect for growth, tea/coffee, and desserts."
        },
        {
            "name": "Amul Taaza Toned Milk",
            "category": "Milk",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 58.0,
            "protein": 3.2,
            "fat": 3.0,
            "carbs": 4.7,
            "sugar": 0.0,
            "sodium": 50.0,
            "serving_size": "200 ml",
            "description": "Fresh toned milk, low in fat and high in nutrients. Ideal for daily tea, coffee, and drinking."
        },
        {
            "name": "Amul Butter",
            "category": "Butter",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 722.0,
            "protein": 0.6,
            "fat": 80.0,
            "carbs": 0.0,
            "sugar": 0.0,
            "sodium": 830.0,
            "serving_size": "10 g",
            "description": "The classic salted butter of India. Made from fresh cream, adds richness to any dish."
        },
        {
            "name": "Amul Processed Cheese",
            "category": "Cheese",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 320.0,
            "protein": 20.0,
            "fat": 26.0,
            "carbs": 1.5,
            "sugar": 0.0,
            "sodium": 1400.0,
            "serving_size": "20 g",
            "description": "Processed cheese block made from wholesome milk. Perfect for grating, melting, and sandwiches."
        },
        {
            "name": "Amul Kool Milk Shake (Kesar)",
            "category": "Milk Shake",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 92.0,
            "protein": 3.0,
            "fat": 3.2,
            "carbs": 13.0,
            "sugar": 8.5,
            "sodium": 45.0,
            "serving_size": "200 ml",
            "description": "Delicious flavored milk shake infused with kesar (saffron) and almonds."
        },
        {
            "name": "Amul Dahi",
            "category": "Dahi",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 62.0,
            "protein": 3.2,
            "fat": 3.1,
            "carbs": 4.4,
            "sugar": 0.0,
            "sodium": 40.0,
            "serving_size": "150 g",
            "description": "Thick, creamy, and pasteurized set curd. Naturally rich in calcium and proteins."
        },
        {
            "name": "Amul Lassi",
            "category": "Lassi",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 74.0,
            "protein": 2.0,
            "fat": 2.1,
            "carbs": 11.7,
            "sugar": 8.0,
            "sodium": 35.0,
            "serving_size": "200 ml",
            "description": "Refreshing traditional Indian yogurt drink. Sweet and soothing."
        },
        {
            "name": "Amul Ice Cream (Vanilla)",
            "category": "Ice Cream",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 200.0,
            "protein": 4.0,
            "fat": 11.0,
            "carbs": 21.0,
            "sugar": 15.0,
            "sodium": 60.0,
            "serving_size": "100 g",
            "description": "Rich vanilla ice cream made from real milk fat, offering a classic smooth taste."
        },
        {
            "name": "Amul Slim & Trim Milk",
            "category": "Milk",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 38.0,
            "protein": 3.3,
            "fat": 0.15,
            "carbs": 5.0,
            "sugar": 0.0,
            "sodium": 50.0,
            "serving_size": "200 ml",
            "description": "Double toned, ultra-low fat milk ideal for weight-conscious individuals and fitness enthusiasts."
        },
        {
            "name": "Amul Paneer",
            "category": "Paneer",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 289.0,
            "protein": 20.0,
            "fat": 22.0,
            "carbs": 2.0,
            "sugar": 0.0,
            "sodium": 20.0,
            "serving_size": "100 g",
            "description": "Fresh cottage cheese. Firm texture, high protein, perfect for paneer butter masala, tikka, and curries."
        },
        {
            "name": "Amul Ghee",
            "category": "Ghee",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 897.0,
            "protein": 0.0,
            "fat": 99.7,
            "carbs": 0.0,
            "sugar": 0.0,
            "sodium": 0.0,
            "serving_size": "10 g",
            "description": "Pure clarified butter fat. Adds a beautiful aroma and rich taste to everyday meals."
        },
        {
            "name": "Amul Masti Buttermilk",
            "category": "Buttermilk",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 29.0,
            "protein": 1.6,
            "fat": 1.5,
            "carbs": 2.3,
            "sugar": 0.0,
            "sodium": 300.0,
            "serving_size": "200 ml",
            "description": "Refreshing spiced buttermilk. Infused with ginger, green chillies, and coriander."
        },
        {
            "name": "Amul Mithai Mate",
            "category": "Dessert Mix",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 335.0,
            "protein": 8.0,
            "fat": 9.0,
            "carbs": 55.5,
            "sugar": 43.0,
            "sodium": 110.0,
            "serving_size": "25 g",
            "description": "Sweetened condensed milk. Smooth, rich, and essential for making Indian desserts."
        },
        {
            "name": "Amul Pro (Protein Drink)",
            "category": "Protein Drink",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 390.0,
            "protein": 8.0,
            "fat": 2.0,
            "carbs": 85.0,
            "sugar": 30.0,
            "sodium": 150.0,
            "serving_size": "30 g",
            "description": "Malt-based nutritional drink powder. Fortified with whey protein, DHA, and essential vitamins."
        },
        {
            "name": "Amul Camel Milk",
            "category": "Milk",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 49.0,
            "protein": 2.8,
            "fat": 2.5,
            "carbs": 3.8,
            "sugar": 0.0,
            "sodium": 70.0,
            "serving_size": "200 ml",
            "description": "100% pure camel milk. Easy to digest and rich in natural insulin-like proteins."
        },
        {
            "name": "Amul Fresh Cream",
            "category": "Cream",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 262.0,
            "protein": 2.0,
            "fat": 25.0,
            "carbs": 3.2,
            "sugar": 0.0,
            "sodium": 40.0,
            "serving_size": "30 g",
            "description": "Low-fat fresh dairy cream. Great for gravies, fruit salads, and desserts."
        },
        {
            "name": "Amul Shrikhand (Elaichi)",
            "category": "Dessert",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 275.0,
            "protein": 6.0,
            "fat": 10.0,
            "carbs": 40.0,
            "sugar": 35.0,
            "sodium": 50.0,
            "serving_size": "100 g",
            "description": "Traditional sweet yogurt dessert flavored with cardamom."
        },
        {
            "name": "Amul Basundi",
            "category": "Dessert",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 210.0,
            "protein": 6.0,
            "fat": 11.0,
            "carbs": 22.0,
            "sugar": 16.0,
            "sodium": 70.0,
            "serving_size": "100 g",
            "description": "Thickened milk dessert cooked with sugar, saffron, and cardamom."
        },
        {
            "name": "Amul Gulab Jamun Mix",
            "category": "Dessert Mix",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 410.0,
            "protein": 12.0,
            "fat": 14.0,
            "carbs": 59.0,
            "sugar": 0.0,
            "sodium": 350.0,
            "serving_size": "50 g",
            "description": "Ready-to-cook dessert mix for making soft and spongy Gulab Jamuns."
        },
        {
            "name": "Amul Cheese Spread (Spicy Garlic)",
            "category": "Cheese",
            "image_url": "/static/images/products/placeholder.png",
            "calories": 278.0,
            "protein": 11.5,
            "fat": 20.0,
            "carbs": 3.0,
            "sugar": 0.0,
            "sodium": 900.0,
            "serving_size": "15 g",
            "description": "Creamy and spreadable cheese with a kick of garlic and spices."
        }
    ]
    
    for p in products_to_seed:
        # Calculate grade using standard DB helper
        grade = calculate_nutri_score(
            calories=p["calories"],
            fat=p["fat"],
            sugar=p["sugar"],
            sodium=p["sodium"],
            protein=p["protein"]
        )
        
        cursor.execute(
            """
            INSERT INTO products (
                name, category, image_url, calories, protein, fat, carbs, sugar, sodium, serving_size, nutrition_grade, description, recipes
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                p["name"], p["category"], p["image_url"], p["calories"], p["protein"],
                p["fat"], p["carbs"], p["sugar"], p["sodium"], p["serving_size"],
                grade, p["description"], recipes_map.get(p["name"], '[]')
            )
        )
        
    # --- Seed Dummy Analytics Information ---
    print("Seeding dummy analytics logs (views, recommendations, goals)...")
    
    # Clear existing logs to avoid compounding records
    cursor.execute("DELETE FROM product_views")
    cursor.execute("DELETE FROM product_recommendations")
    cursor.execute("DELETE FROM health_profiles")
    cursor.execute("DELETE FROM scan_history")
    cursor.execute("DELETE FROM meal_plans")

    # Get mapped products
    cursor.execute("SELECT id, name FROM products")
    seeded_prods = cursor.fetchall()
    product_map = {row['name']: row['id'] for row in seeded_prods}

    # Generate dummy users and goals data
    import random
    goals = ['weight_loss', 'muscle_gain', 'maintenance', 'diabetes']
    diet_types = ['vegetarian', 'none']
    lifestyles = ['sedentary', 'active', 'moderate']
    
    for i in range(1, 35):
        email = f"user{i}@amulnutri.ai"
        cursor.execute("SELECT id FROM users WHERE email = ?", (email,))
        user_row = cursor.fetchone()
        if not user_row:
            cursor.execute(
                "INSERT INTO users (name, email, password_hash, role) VALUES (?, ?, ?, ?)",
                (f"Demo User {i}", email, "demo123", "user")
            )
            u_id = cursor.lastrowid
        else:
            u_id = user_row['id']
            
        # Create health profile
        cursor.execute(
            "INSERT OR REPLACE INTO health_profiles (user_id, age, weight, height, goal, diet_type, lifestyle, health_conditions) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (u_id, random.randint(20, 55), random.uniform(55.0, 90.0), random.uniform(155.0, 185.0), random.choice(goals), random.choice(diet_types), random.choice(lifestyles), "")
        )

    # Distribute views (Total views ~350)
    popular_products = [
        "Amul Gold Full Cream Milk", 
        "Amul Butter", 
        "Amul Processed Cheese", 
        "Amul Paneer", 
        "Amul Ice Cream (Vanilla)"
    ]
    for p_name in popular_products:
        if p_name in product_map:
            p_id = product_map[p_name]
            for _ in range(random.randint(35, 60)):
                cursor.execute("INSERT INTO product_views (product_id, user_id) VALUES (?, ?)", (p_id, random.randint(1, 34)))

    for p_name, p_id in product_map.items():
        if p_name not in popular_products:
            for _ in range(random.randint(5, 15)):
                cursor.execute("INSERT INTO product_views (product_id, user_id) VALUES (?, ?)", (p_id, random.randint(1, 34)))

    # Distribute recommendations (Total recs ~180)
    healthy_products = [
        "Amul Slim & Trim Milk",
        "Amul Dahi",
        "Amul Masti Buttermilk",
        "Amul Paneer"
    ]
    for p_name in healthy_products:
        if p_name in product_map:
            p_id = product_map[p_name]
            for _ in range(random.randint(20, 40)):
                cursor.execute("INSERT INTO product_recommendations (product_id, user_id, type) VALUES (?, ?, ?)", (p_id, random.randint(1, 34), 'recommend'))

    avoid_products = [
        "Amul Butter",
        "Amul Ice Cream (Vanilla)",
        "Amul Mithai Mate"
    ]
    for p_name in avoid_products:
        if p_name in product_map:
            p_id = product_map[p_name]
            for _ in range(random.randint(12, 25)):
                cursor.execute("INSERT INTO product_recommendations (product_id, user_id, type) VALUES (?, ?, ?)", (p_id, random.randint(1, 34), 'avoid'))
        
    conn.commit()
    conn.close()
    print("Successfully seeded dummy products and analytics history!")

if __name__ == "__main__":
    copy_placeholder()
    seed_data()
